name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout your repository using git
        uses: actions/checkout@v4
      
      - name: Install pnpm
        run: |
          npm install -g pnpm
      
      - name: Install, build, and upload your site
        uses: withastro/action@v3
        with:
          path: . # The root location of your Astro project inside the repository.
          node-version: 20 # Specify the version of Node.js, you can change it if needed.
          package-manager: pnpm@latest # Explicitly specify pnpm for the package manager.

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
